### ISSUE TITLE
The `Constraint` methods aren't being used

### ISSUE THREAD

**Issue by athanclark** [mgrabmueller/AlgorithmW#2]
Thank you for supplying this package, it's been invaluable for me while developing [ltext](github.com/ltext/ltext). However, near the bottom of your document, there's some machinery for constraint building, but not solving. Is there a paper you can direct me toward for solving this list of constraints? I would be very grateful :)

**Comment by mgrabmueller** [comment]
Thanks for trying out the code, and I'm glad it was useful!

Regarding the constraint code, I had totally forgotten about that, and I don't even remember when I wrote it.  I think it was from an attempt to implement the bottom-up type inference from [Generalizing Hindley-Milner Type Inference Algorithms](http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.18.9348) by Bastiaan Heeren, Jurriaan Hage and Doaitse Swierstra.

I hope this helps!

**Comment by athanclark** [comment]
Thank you!!
